### ISSUE TITLE
hw2 submission!

### ISSUE THREAD

**Issue by zpcohen** [kingcohn1/stat679work#3]
@cecileane

**Comment by cecileane** [comment]
Hi Zach,
Very nice job! Your script worked well. More details below.

## overall presentation

In general, it's good to get into the habit of separating the scripts and input/output files into different directories.

Your readme file had very clear instructions, and I think it's great that you show what to expect if the arguments are given in an incorrect order. Doing so gives a cryptic error message, so the warning in your readme file is helpful.
It would have been even better to use the argparse module to read/use arguments. This module makes it really easy to write user-friendly scripts that give helpful messages when arguments are not as expected.

You made great use of markdown style.

## running your script

When I ran your script I got a weird output on the screen:

```shell
$ python hw2.py waterTemperature.csv energy.csv  myout.csv
Row,Date & Time,Temperature,Energy(Wh/1000)

<_io.TextIOWrapper name='myout.csv' mode='w' encoding='UTF-8'>
```

but the new file was just perfect. Trying to get the output to STDOUT almost worked too, except for the header being printed twice and a blank line in between:

```shell
$ python hw2.py waterTemperature.csv energy.csv > myout.csv
Traceback (most recent call last):
  File "hw2.py", line 131, in <module>
    print(output)
NameError: name 'output' is not defined

$ head -n 6 myout.csv
Row,Date & Time,Temperature,Energy(Wh/1000)

Row,Date & Time,Temperature,Energy(Wh/1000)
1,07/29/16 10:26:34 AM,72.86,
2,07/29/16 11:26:34 AM,73.92,
3,07/29/16 12:26:34 PM,73.98,
```

## about your code

Your code would benefit from being broken down into separate functions. You don't have any function, but there are separate tasks (read the temperature file, read the energy file, and then write the output file) that could have been handled by separate functions. For instance, having a function to write the `merge_list` content would have avoided copy-paste (and associated sneak-in bugs) on lines 103-106, 113-116, 119-122 and 126-129.

On line 25 you name a variable `time`. This is a poor choice, between `time` was already defined as a module that you imported: `import time` (line 2).

It's great that checked for the existence of the output file, before overwriting it. :)

Line 98 and the last line (`print(output)`) are the culprits for the quirks I had when I ran your script.

Nice use of regular expressions!
